# Generated by Django 5.2.3 on 2025-06-23 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guerra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('alianza_enemiga', models.CharField(max_length=100)),
                ('en_curso', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enemigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('coordenadas', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('ultima_vez_atacado', models.DateTimeField(blank=True, null=True)),
                ('guerra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemigos', to='app_guerra.guerra')),
            ],
        ),
        migrations.CreateModel(
            name='MejoraEdificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edificio', models.CharField(max_length=100)),
                ('nivel_inicial', models.IntegerField()),
                ('nivel_objetivo', models.IntegerField()),
                ('fecha_inicio', models.DateTimeField()),
                ('duracion_horas', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MiembroAlianza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jugador', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('guerra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='app_guerra.guerra')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango', models.CharField(choices=[('soldado', 'Soldado'), ('capitan', 'Capitán'), ('general', 'General')], default='soldado', max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
