# Generated by Django 5.2.3 on 2025-06-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_guerra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mejoraedificio',
            name='categoria',
            field=models.CharField(choices=[('recursos', 'Recursos'), ('ejercito', 'Ejército'), ('torretas', 'Torretas'), ('defensas', 'Defensas'), ('base_estelar', 'Base Estelar')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mejoraedificio',
            name='numero_colonia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mejoraedificio',
            name='planeta_principal',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mejoraedificio',
            name='edificio',
            field=models.CharField(max_length=30),
        ),
    ]
