# Generated by Django 5.2.3 on 2025-06-23 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_guerra', '0002_mejoraedificio_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroAlianzaPropia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('guerra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros_propios', to='app_guerra.guerra')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_guerra.perfil')),
            ],
        ),
    ]
