# Generated by Django 5.2.3 on 2025-06-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_guerra', '0003_miembroalianzapropia'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembroalianzapropia',
            name='alias_juego',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='miembroalianzapropia',
            name='estrellas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='miembroalianzapropia',
            name='nivel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='miembroalianzapropia',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
